config/routes.rb
Rails.application.routes.draw do
root :to => 'bookers#top'
 resources :bookers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true
	validates :title, presence: true
	validates :body, presence: true
end

app/models/booker.rb
class Booker < ApplicationRecord
	# default_scope -> { order(created_at: :'DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	add_flash_types :success, :info, :warning, :danger
end

app/controllers/bookers_controller.rb
class BookersController < ApplicationController
  def index
  	@bookers = Booker.all
  	@booker = Booker.new
  end

  def top
  end

  def show
  	@booker = Booker.find(params[:id])
  end

  def edit
  	@booker = Booker.find(params[:id])
  end
  def update
  	booker = Booker.find(params[:id])
  	booker.update(booker_params)
  	flash[:success] = "Book was successfully updated."
  	redirect_to booker_path(booker.id)
  end

  def create
  	@booker = Booker.new(booker_params)
    @bookers = Booker.all
    if @booker.save
      flash[:success] = "Book was successfully created."
      redirect_to booker_path(@booker.id)
    else
      render 'index'

    end

  end

  def destroy
  	booker = Booker.find(params[:id])
  	booker.destroy
  	flash[:success] = "Book was successfully destroyed."
  	redirect_to bookers_path
  end

  private
  def booker_params
  	params.require(:booker).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/views/bookers/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@booker, url:"/bookers/#{@booker.id}") do |f| %>
		<div class="field">
			<label for = "book_title">Title</label><br>
			<%= f.text_field :title, id: "book_title" %>
		</div>
		<div class="field">
			<label for = "book_body">Body</label><br>
			<%= f.text_field :body, id: "book_body" %>
		</div>
			<%= f.submit 'Update Book' %> <br><br>

    <%= link_to 'Show', booker_path(@booker.id) %> 
     | 
	<%= link_to 'Back', bookers_path %> 
<% end %>

app/views/bookers/index.html.erb
<body>
	<% flash.each do |message_type, message| %>
　	<p class="alart"><%= message %></p>
	<% end %>
	<h1>Books</h1>
	<table>
	 	<thead>
			<tr>
				<th>Title</th>
				<th>body</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		 </thead>
		 <tbody>
			<tr>
				<% @bookers.each do |booker| %>
					<th><%= booker.title %></th>
					<th><%= booker.body %></th>
					<th> <%= link_to 'Show',booker_path(booker.id) %></th>
					<th><%= link_to 'Edit', edit_booker_path(booker.id) %></th>
					<th><%= link_to "Destroy", booker_path(booker.id), method: :delete, "data-confirm" => "Are you sure?" %></th>
				
			</tr>
			<% end %>
		 </tbody>
	</table>

	<h2>New book</h2>
	<%= form_for(@booker, url:"/bookers") do |f| %>
			<% if @booker.errors.any? %>
				<div class="alart-message">
					 <h3 class="alart-body"><%= pluralize(@booker.errors.count, "error") %> prohibited this book from being saved:</h3>
    			<ul>
     				 <% @booker.errors.full_messages.each do |message| %>
       					 <li><%= message %></li>
     				 <% end %>
    			</ul>
		  <% end %>
      		</div>

		<div class="field">
			<label for = "book_title">Title</label>
			<%= f.text_field :title, id: "book_title" %>
		</div>
		<div class="field">
			<label for = "book_body">Body</label>
			<%= f.text_field :body, id: "book_body" %>
		</div>
			<%= f.submit 'Create Book' %> 
	<% end %>

</body>

app/views/bookers/show.html.erb
<% flash.each do |message_type, message| %>
　	<div class="alart"><%= message %></div>
<% end %>
<body>
	<p>
		<strong>Title: </strong>
		<%= @booker.title %>
	</p>
	<p>
		<strong>Body: </strong>
		<%= @booker.body %>
	</p>

	<%= link_to 'Edit', edit_booker_path(@booker.id) %>
	 | 
	<%= link_to 'Back', bookers_path %>

</body>

app/views/bookers/top.html.erb
<body>
	<h1>ようこそ <strong> Bookers</strong> へ！</h1>

	<p><strong>Bookers </strong>では、さまざまな書籍に関するあなたの意見や</p>
	<p>印象を共有し交換することができます</p>
	<p> <%= link_to 'start', bookers_path %> </p>

</body>

app/views/layouts/application.html 2.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/mailer.html 2.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/mailer.text 2.erb
<%= yield %>